# Generated by Django 2.1.7 on 2019-04-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
