# Generated by Django 2.1.7 on 2019-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0002_auto_20190402_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_answers',
            field=models.FileField(null=True, upload_to='answers'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_question',
            field=models.FileField(null=True, upload_to='question'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
