# Generated by Django 2.1.7 on 2020-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0005_feedback_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
