# Generated by Django 2.1.7 on 2020-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0006_auto_20200408_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
