# Generated by Django 2.1.7 on 2020-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0007_auto_20200412_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
