# Generated by Django 2.1.7 on 2020-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_sample', '0008_auto_20200412_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
